// Code generated by qtc from "mobile.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// <!--
//  * @Descripttion:
//  * @version:
//  * @Author: Wynters
//  * @Date: 2021-04-27 14:30:27
//  * @LastEditors: Wynters
//  * @LastEditTime: 2021-04-30 17:05:26
// -->

//line templates/admin/errors/mobile.qtpl:9
package errors

//line templates/admin/errors/mobile.qtpl:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/admin/errors/mobile.qtpl:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/admin/errors/mobile.qtpl:10
type Mobile struct {
	Vars map[string]interface{}
}

//line templates/admin/errors/mobile.qtpl:14
func (m *Mobile) StreamBody(qw422016 *qt422016.Writer) {
//line templates/admin/errors/mobile.qtpl:14
	qw422016.N().S(`

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
    `)
//line templates/admin/errors/mobile.qtpl:22
	qw422016.N().S(`
    <meta name="description" content="延初OA系统">
    <meta name="author" content="浙江延初集团有限公司">
    <link rel="shortcut icon" href="/favicon.ico" /> <!-- Bootstrap Core CSS -->
    <link href="http://fw.yunxi.top/static/css/bootstrap.min.css" rel="stylesheet">
    <title>`)
//line templates/admin/errors/mobile.qtpl:27
	qw422016.E().V(m.Vars["title"])
//line templates/admin/errors/mobile.qtpl:27
	qw422016.N().S(`</title>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]> <script src="https://cdn.staticfile.org/html5shiv/3.7.3/html5shiv.min.js"></script> <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script> <![endif]-->
</head>
<body>
    <div style="width: 80%;margin: 0 auto;margin-top: 100px;" align="center">
        <div><img src="/static/img/img.png" style="width: 50%;" /></div>
        <h3 style="margin-top:10px">请使用PC端打开本系统</h3>
    </div>
    </body>
`)
//line templates/admin/errors/mobile.qtpl:37
}

//line templates/admin/errors/mobile.qtpl:37
func (m *Mobile) WriteBody(qq422016 qtio422016.Writer) {
//line templates/admin/errors/mobile.qtpl:37
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/admin/errors/mobile.qtpl:37
	m.StreamBody(qw422016)
//line templates/admin/errors/mobile.qtpl:37
	qt422016.ReleaseWriter(qw422016)
//line templates/admin/errors/mobile.qtpl:37
}

//line templates/admin/errors/mobile.qtpl:37
func (m *Mobile) Body() string {
//line templates/admin/errors/mobile.qtpl:37
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/admin/errors/mobile.qtpl:37
	m.WriteBody(qb422016)
//line templates/admin/errors/mobile.qtpl:37
	qs422016 := string(qb422016.B)
//line templates/admin/errors/mobile.qtpl:37
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/admin/errors/mobile.qtpl:37
	return qs422016
//line templates/admin/errors/mobile.qtpl:37
}
